### ISSUE TITLE
KEY值硬编码到so中安全吗？

### ISSUE THREAD

**Issue by githemiao** [BruceWind/AESJniEncrypt#43]
用16进制打开so，不就能看见KEY值吗？  这个怎么能保证安全的？

**Comment by BruceWind** [comment]
Hi, bro. may I be late for reply.

---

Very appreciate your issue.
I don't recommend writing the key into code despite native code.
I have said something about this issue in READE. 

------
One way I wrote in READ is split the key.
You can modify `getKey()` function.  
In that function you can merge several slices which you split. 
Due to the fact that code or function are safety, the key will be safe though.

**Comment by BruceWind** [comment]
The Chinese README write:

**手工处理隐藏key,最复杂的方案：将密钥分成不同的几段,存储在不同的代码中,最后将他们拼接起来,可以将整个操作写的很复杂,增加逆向难度。（目前代码里用的是稍微简单的方案）**.

Thanks about your issue.

**Comment by BruceWind** [comment]
I'm going to close this issue in case there is no more questions. And I think I have reply it enough and clearly.
